### ISSUE TITLE
When will the first part of the code can be released? Thanks!

### ISSUE THREAD

**Issue by lllllllllllll-llll** [zhuhancheng/MetaIQA#2]
Hello! The overall framework of the MetaIQA is composed of two steps: 1. meta-training for quality prior model and fine-tuning for NR-IQA of unknown distortions. When will the first part of the code can be released? Thanks!

**Comment by zhuhancheng** [comment]
MetaIQA_On_TID2013_KADID.py  is used for training quality prior model
