### ISSUE TITLE
Error with model loading

### ISSUE THREAD

**Issue by esafronova** [zhuhancheng/MetaIQA#3]
Hello! I was trying to open the both trained models with torch.load('MetaIQA/model_IQA/TID2013_IQA_Meta_resnet18.pt') and got this error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-9442784ff936> in <module>()
----> 1 model = torch.load('MetaIQA/model_IQA/TID2013_IQA_Meta_resnet18.pt')

/usr/local/lib/python3.6/dist-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    591                     return torch.jit.load(f)
    592                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 593         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    594 
    595 

/usr/local/lib/python3.6/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    771     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    772     unpickler.persistent_load = persistent_load
--> 773     result = unpickler.load()
    774 
    775     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

AttributeError: Can't get attribute 'Net' on <module '__main__'>

I tried it in my local environment and using colab, so the same error occurs with different python and pycharm versions.
Could you, please, specify the exact versions or maybe check the both models.

**Comment by zhuhancheng** [comment]
Our code is implemented with Python 3.6, Pytorch 0.4, Pycharm 2017-community.

**Comment by ainnn** [comment]
same issue with py3.6.9/torch1.5.1(cpu) and py3.5.2/torch0.4.0(gpu) when using the provided pretrained models.

**Comment by zhuhancheng** [comment]
The pre-trained model  must use GPU to run. The code is implemented with Python 3.6.0 and python 0.4.1.

**Comment by ainnn** [comment]
solved. the definitions of class Net and  BaselineModel1 are supposed to add first before using torch.load(). but i still have problems in using load_state_dict() in latter steps. 
@zhuhancheng , can you provide a script to show how to use the pretrained model to do inference? thx.

**Comment by ainnn** [comment]
solved. the definitions of class Net and BaselineModel1 are supposed to add first before using torch.load().
